#page title
page_title                                : CVNDY (/ˈkan-dē/) - Automotive Platform                                       # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                :                                 # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).

appstore_link                             :                                           # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            :                                           # Enter Google Play Store URL.
presskit_download_link                    : https://awwwry.com                                          # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : ./assets/candy-app-icon.png                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  : CVNDY.                                       # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : A new type of automotive platform — designed for enthusiasts, by enthusiasts.

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : '@AWWWRY'                                
your_link                                 : https://awwwry.com                     
your_city                                 : USA                                
email_address                             : 
facebook_username                         :                                           
instagram_username                        : 
twitter_username                          : 
github_username                           : 
youtube_username                          :



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : CVNDY
    description                           : Pronounced candy, is a new platform for gearheads.
    fontawesome_icon_name                 : car-side
    
  - title                                 : Available on iPhone
    description                           : Initial release will be available on iOS; Android to follow.
    fontawesome_icon_name                 : mobile

  - title                                 : Broadcast
    description                           : Live stream tutorials, discussions — everything in between.
    fontawesome_icon_name                 : play-circle

  - title                                 : Community
    description                           : Teach and learn with other enthusiasts.
    fontawesome_icon_name                 : comments

  - title                                 : Earn Money
    description                           : Sell, trade or promote for extra income.
    fontawesome_icon_name                 : money-bill-wave
  
  - title                                 : And More
    description                           : 'So much more — <a href="./changelog/" title="Changelog">stay updated</a>.'
    fontawesome_icon_name                 : ellipsis-h

  - title                                 : # New Feature Title
    description                           : # New Feature Description
    fontawesome_icon_name                 : # Enter Font Awesome icon name (e.g. star). Find icons on fontawesome.com/icons.



# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.0
topbar_title_color                        : "#ffffff"

cover_image                               : https://media.giphy.com/media/9cFl8zwd5hdK0/giphy.gif                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#30444E"
cover_overlay_transparency                : 0.4

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#ffffff"

link_color                                : "#FF565E"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#ffffff"
feature_icons_background_color            : "#FF565E"

social_icons_foreground_color             : "#ffffff"
social_icons_background_color             : "#000000"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown

compress_html:
  clippings: all
  comments: [""]
  endings: [html, head, body, li, dt, dd, rt, rp, optgroup, option, colgroup, caption, thead, tbody, tfoot, tr, td, th]
  profile: false
  blanklines: false
  ignore:
    envs: []
